package com.example.movieapp.model

data class movieData(val id: String,
    val title: String,
    val description: String,
    val poster: String,
    val image: List<String>,
    val rating: String,
    val year: String,
    val actor: String,
    val genre: String,
    ) {
}

fun getData():List<movieData>{
    return listOf(
        movieData(id = "1",
        title = "Inception",
        poster = "https://m.media-amazon.com/images/I/61Ug+K8o5FL.jpg",
        image = listOf("https://m.media-amazon.com/images/I/61Ug+K8o5FL.jpg"),
        description = "A mind-bending heist thriller directed by Christopher Nolan.",
        rating = "8.8",
        year = "2010",
        actor = "Leonardo DiCapri, Joseph Gordon-Levitt, Ellen Page",
        genre = "Sci-Fi, Action, Adventure"),

        movieData(id = "2",
        title = "The Shawshank Redemption",
        poster = "shawshank_poster.jpg",
        image = listOf("https://stephenking.com/images/movies/theatrical_movie/the_shawshank_redemption/us2.jpg"),
        description = "A gripping tale of hope and friendship in the confines of Shawshank prison.",
        rating = "9.3",
        year = "1994",
        actor = "Tim Robbins, Morgan Freeman",
        genre = "Drama, Crime"),

        movieData(id = "3",
        title = "The Dark Knight",
        poster = "dark_knight_poster.jpg",
        image = listOf("https://irs.www.warnerbros.com/keyart-jpeg/movies/media/browser/the_dark_knight_key_art.jpg"),
        description = "Batman faces the Joker in a battle of chaos and order.",
        rating = "9.0",
        year = "2008",
        actor = "Christian Bale, Heath Ledger, Aaron Eckhart",
        genre = "Action, Crime, Drama"),

        movieData(id = "4",
        title = "Forrest Gump",
        poster = "forrest_gump_poster.jpg",
        image = listOf("https://cdn.artphotolimited.com/images/5b9fc1ecac06024957be8806/1000x1000/forrest-gump-avec-tom-hanks.jpg"),
        description = "A man with a low IQ accomplishes great things in his life.",
        rating = "8.8",
        year = "1994",
        actor = "Tom Hanks, Robin Wright",
        genre = "Drama, Romance"),

        movieData(id = "5",
        title = "Avatar",
        poster = "avatar_poster.jpg",
        image = listOf("https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@.jpg"),
        description = "A paraplegic marine becomes part of the Avatar Program on Pandora.",
        rating = "7.8",
        year = "2009",
        actor = "Sam Worthington, Zoe Saldana, Sigourney Weaver",
        genre = "Action, Adventure, Fantasy"),

        movieData(id = "6",
        title = "Pulp Fiction",
        poster = "pulp_fiction_poster.jpg",
        image = listOf("https://images-na.ssl-images-amazon.com/images/I/6195vKT66eL.jpg"),
        description = "A nonlinear narrative intertwining several stories of crime and redemption.",
        rating = "8.9",
        year = "1994",
        actor = "John Travolta, Uma Thurman, Samuel L. Jackson",
        genre = "Crime, Drama"),

        movieData(id = "7",
        title = "The Matrix",
        poster = "matrix_poster.jpg",
        image = listOf("https://m.media-amazon.com/images/M/MV5BODE0MzZhZTgtYzkwYi00YmI5LThlZWYtOWRmNWE5ODk0NzMxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@.jpg"),
        description = "A computer hacker discovers a dystopian world controlled by machines.",
        rating = "8.7",
        year = "1999",
        actor = "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
        genre = "Action, Sci-Fi"),

        movieData(id = "8",
        title = "The Godfather",
        poster = "godfather_poster.jpg",
        image = listOf("https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1675701488-the-godfather-peacock-1675701462.jpg?crop=1xw:1xh;center,top&resize=980:*"),
        description = "The patriarch of a powerful crime family hands over control to his reluctant son.",
        rating = "9.2",
        year = "1972",
        actor = "Marlon Brando, Al Pacino, James Caan",
        genre = "Crime, Drama"),

        movieData(id = "9",
        title = "Interstellar",
        poster = "interstellar_poster.jpg",
        image = listOf("https://m.media-amazon.com/images/I/51FypHhrzES.jpg"),
        description = "A group of explorers travels through a wormhole in search of a new home for humanity.",
        rating = "8.6",
        year = "2014",
        actor = "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
        genre = "Sci-Fi, Adventure, Drama"),

        movieData(id = "10",
        title = "The Silence of the Lambs",
        poster = "silence_of_the_lambs_poster.jpg",
        image = listOf("https://images-na.ssl-images-amazon.com/images/I/71wytopNhPL.jpg"),
        description = "An FBI agent seeks the help of a brilliant but insane serial killer to catch another killer on the loose.",
        rating = "8.6",
        year = "1991",
        actor = "Jodie Foster, Anthony Hopkins",
        genre = "Crime, Drama, Thriller"),

    )

}

